name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # ✅ Updated version

      - name: Install dependencies
        working-directory: blog_app_frontend
        run: flutter pub get

      - name: Analyze & Build
        working-directory: blog_app_frontend
        run: |
          flutter analyze
          flutter build apk

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: blog_app_frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
